<section class="topbar-left-flyout">
    <a href="#" class="action-menu">
        <span><i class="fa fa-bars"></i></span>
    </a>
    <div class="logo">
        <a href="#">
            Crafty!
        </a>
    </div>
    <nav>
        <ul>
            <li>
                <h3>
                    Menu
                </h3>
            </li>
            <li>
                <a href="#">Item - 1</a>
            </li>
        </ul>
    </nav>
    <div class="overlay"></div>
</section>